import React from 'react';

const PrivacyPolicy = () => {
  return (
    <div className="bg-black text-gray-800 leading-relaxed p-6 md:p-10 max-w-4xl mx-auto font-sans pt-20 pb-20 px-6 md:px-12 lg:px-24 py-8 ">
      <h1 className="text-3xl md:text-4xl font-bold mb-8 text-center">Terms & Conditions</h1>
      {/* Legal Disclaimer */}
      <p className="text-xs md:text-sm text-red-600 font-bold mb-6 leading-tight">
        THIS DOCUMENT IS AN ELECTRONIC RECORD IN TERMS OF INFORMATION TECHNOLOGY ACT, 2000 AND RULES THEREUNDER AS APPLICABLE AND THE AMENDED PROVISIONS PERTAINING TO ELECTRONIC RECORDS IN VARIOUS STATUTES AS AMENDED BY THE INFORMATION TECHNOLOGY ACT, 2000. THIS ELECTRONIC RECORD IS GENERATED BY A COMPUTER SYSTEM AND DOES NOT REQUIRE ANY PHYSICAL OR DIGITAL SIGNATURES. THIS DOCUMENT IS PUBLISHED IN ACCORDANCE WITH THE PROVISIONS OF RULE 3(1) OF THE INFORMATION TECHNOLOGY (INTERMEDIARIES GUIDELINES) RULES, 2011 THAT REQUIRE PUBLISHING THE RULES AND REGULATIONS, TERMS OF SERVICE, PRIVACY POLICY AND USER AGREEMENT FOR ACCESS OR TERMS OF USAGE OF www.cheloride.com (HEREINAFTER REFERRED TO AS THE "SITE"). YOUR USE OF THIS SITE, OR YOUR PROVISION OF ANY PERSONAL INFORMATION CONSTITUTES YOUR AGREEMENT TO THESE TERMS AND ANY SUBSEQUENT CHANGES TO THESE TERMS; DO NOT USE THE SITE OR PROVIDE INFORMATION IF YOU DO NOT AGREE WITH ALL OF THE TERMS.
      </p>

      {/* Privacy Notice */}
      <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4 border-b pb-2">Privacy Notice</h2>
      <p className="mb-6 text-gray-700">
        Though we make every effort to preserve user privacy, we may need to disclose personal information when required by law wherein we have a good-faith belief that such action is necessary to comply with an appropriate law enforcement investigation, current judicial proceeding, a court order or legal process served on our Site, or as required by law. We may also need to disclose personal information to a third party for the purpose of delivering services to users.
      </p>

      {/* General Description */}
      <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4 border-b pb-2">General Description</h2>
      <p className="mb-4 text-gray-700">
        The Site may collect a user's name, postal address, telephone number, mobile number, email address. Besides the above, Members intending to create an account may be asked to submit personal information including driving license, proof of identity, job ID or student ID, GST registration (in case of business holders), and information pertaining to the Member's credit card/debit card or bank account details. The Site may also be required to collect PAN card details and any such detail relevant to carry out the transaction.
      </p>
      <p className="mb-4 text-gray-700">
        This information is requested when the user is entering into a transaction and is further used to deliver the services as requested. The data collected will also be used to manage the Site and detect fraud or site abuse.
      </p>
      <ul className="list-disc list-inside space-y-2 text-gray-700 ml-4 mb-6">
        <li><strong>Vehicle Use Data:</strong> Vehicles contain hardware that gathers and transmits information about vehicle use for security against accidents or theft and to provide valuable services such as driver data sharing.</li>
        <li><strong>Location Tracking:</strong> We track your vehicle’s location to prevent theft and assist in emergencies. Your location remains within Chelo Ride services and is not publicly disclosed. It may be shared with insurance companies, police, or similar parties during investigations, accident claims, or emergency assistance.</li>
        <li><strong>Driver and Vehicle Information:</strong> As a customer, you authorize us to access your driver’s record and vehicle history from all applicable authorities (e.g., DMV, RMV, mechanics). This authorization continues as long as you remain a customer. You may withdraw consent at any time by closing your account.</li>
      </ul>

{/* Refund Policy */}
<h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4 border-b pb-2">Refund Policy</h2>
<p className="mb-4 text-gray-700">
  At Chelo Ride, customer satisfaction is important to us. Our refund policy is as follows:
</p>

{/* Eligibility */}
<h3 className="text-xl font-semibold text-gray-800 mt-6 mb-2">Eligibility</h3>
<ul className="list-disc list-inside space-y-2 text-gray-700 ml-4">
  <li>Refund requests must be made within <strong>7 days</strong> of the original transaction.</li>
  <li>Refunds are applicable only for services that have not yet been used, initiated, or completed.</li>
  <li>No refunds will be provided for promotional or discounted services unless legally required.</li>
</ul>

{/* Processing & Credit Timeframe */}
<h3 className="text-xl font-semibold text-gray-800 mt-6 mb-2">Processing &amp; Credit Timeframe</h3>
<ul className="list-disc list-inside space-y-2 text-gray-700 ml-4">
  <li>Post approval of your refund request, we will process the refund within <strong>3–5 business days</strong>.</li>
  <li>Once processed, the refund will be credited to your original payment method within <strong>5–10 business days</strong>, depending on your bank or payment provider.</li>
</ul>

{/* Disputes */}
<h3 className="text-xl font-semibold text-gray-800 mt-6 mb-2">Disputes</h3>
<p className="text-gray-700 mb-4">
  In case of disputes, our support team will review and respond within <strong>72 hours</strong> of receiving your request.
</p>

{/* How to Request a Refund */}
<h3 className="text-xl font-semibold text-gray-800 mt-6 mb-2">How to Request a Refund</h3>
<p className="text-gray-700">
  Please contact our customer support team at <strong>dreamcarsvizag@gmail.com</strong> to request a refund.
</p>

<br />


      {/* Collection and Use of Non-Personal Information */}
      <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4 border-b pb-2">Collection and Use of Non-Personal Information</h2>
      <p className="mb-6 text-gray-700">
        We collect non-personal information — data that does not directly identify you — such as IP addresses, usage details, and identifying technologies. We may use, transfer, collect, and disclose this information for any purpose. If non-personal information is combined with personal information, the combined data will be treated as personal information for as long as it remains linked.
      </p>

      {/* Aggregate Information */}
      <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4 border-b pb-2">Aggregate Information</h2>
      <p className="mb-6 text-gray-700">
        We may share non-personally identifiable information (such as referring/exit pages, anonymous usage data, URLs, platform types, number of clicks) with third parties to help them understand usage patterns of Chelo Ride services.
      </p>
      <p className="mb-6 text-gray-700">
        Third-party ad servers or networks may serve ads on the Chelo Ride Site. These may automatically receive your IP address and use technologies like cookies, JavaScript, or web beacons to measure ad effectiveness and personalize content. We do not provide personally identifiable information to these parties without your consent. However, if you respond to an ad targeted at a specific audience, the advertiser may infer you fit that audience. Our Privacy Policy does not apply to third-party advertisers, and we cannot control their activities.
      </p>

      {/* Normal Browsing */}
      <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4 border-b pb-2">Normal Browsing</h2>
      <p className="mb-6 text-gray-700">
        When you browse, read, or download content from the Site, we collect data such as your IP address, URL request, browser type, and date/time of access. We collect visitor IP addresses, access times, browser types, and visited web pages. No other information is collected without your knowledge and permission.
      </p>

      {/* Information You Provide */}
      <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4 border-b pb-2">Information You Provide</h2>
      <p className="mb-6 text-gray-700">
        The Site requests personally identifiable information when you use the "Contact Us" feature, subject to the Terms of Use. This may include your name, email address, and location, and is used for research, site usability improvements, mailing lists, or service-related activities.
      </p>
      <p className="mb-6 text-gray-700">
        This data is securely stored and not sold or disclosed to third parties beyond what is outlined in this policy. You may request deletion of your account and associated personal data via email or through the "Manage Profile" section in the app or website.
      </p>

      {/* Disclosure of Information */}
      <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4 border-b pb-2">Disclosure of Information</h2>
      <p className="mb-4 text-gray-700">
        Log records and server data may be accessed by our system administrators. If legally required (e.g., court order), we may disclose your information. While we aim to challenge overly broad requests, we cannot guarantee success in all cases. If you do not contest the request, we may be obligated to comply.
      </p>
      <p className="mb-4 text-gray-700">
        Data may be shared with:
      </p>
      <ul className="list-disc list-inside space-y-2 text-gray-700 ml-4 mb-6">
        <li>Group companies, agents, and subcontractors for service delivery, payment collection, data analysis, marketing, and customer support.</li>
        <li>Parties involved in fraud protection, credit risk reduction, or legal proceedings.</li>
        <li>New entities in the event of a sale, merger, amalgamation, or demerger of our business.</li>
        <li>Third-party partners (e.g., ride-sharing, parking services) when you register for or purchase their services via Chelo Ride.</li>
      </ul>
      <p className="mb-6 text-gray-700">
        Participation in rewards, discounts, contests, or third-party programs authorizes us to share your information under contractual agreements. We only share information necessary for service provision, and such sharing is governed by privacy agreements. By providing this consent, you acknowledge that Chelo Ride is not liable for third-party actions.
      </p>

      {/* Security */}
      <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4 border-b pb-2">Security</h2>
      <p className="mb-6 text-gray-700">
        We employ technical and organizational security measures to protect your personal information from unauthorized access, loss, or damage. However, when you use our services or post content, some information (e.g., name, email) may become visible to other users. You are responsible for what you choose to share publicly.
      </p>
      <p className="mb-6 text-gray-700">
        You are also responsible for maintaining the confidentiality of your account credentials and restricting access to your device. We are not liable for third-party access resulting from unauthorized use of your account.
      </p>

      {/* Log Files */}
      <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4 border-b pb-2">Log Files</h2>
      <p className="mb-6 text-gray-700">
        We use log files to record IP addresses, browser type, ISP, referring/exit pages, platform type, timestamp, and click counts. This helps analyze trends, administer the site, track aggregate user movement, and gather demographic data. IP addresses are not linked to personally identifiable information and may be used for advertising and promotional targeting.
      </p>

      {/* Cookies */}
      <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4 border-b pb-2">Cookies</h2>
      <p className="mb-6 text-gray-700">
        We use session cookies to recognize returning users and enhance functionality. Anonymous visitors receive cookies while browsing. Registered users receive cookies upon login. These help improve user experience and site functionality.
      </p>

      {/* Posting */}
      <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4 border-b pb-2">Posting</h2>
      <p className="mb-6 text-gray-700">
        Posting content is a public action governed by Chelo Ride’s Membership Terms and Conditions. Your name and other identifiers may be displayed with your contributions. All content may be retained for archival, restoration, or research purposes. Editing or deleting content changes its visibility but does not permanently erase it from our systems.
      </p>

      {/* Other Websites */}
      <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4 border-b pb-2">Other Websites</h2>
      <p className="mb-6 text-gray-700">
        While on our Site, any personal information you provide is shared only with us. However, links may direct you to external, independently operated websites. We are not responsible for their privacy practices or content. We encourage you to review the privacy policies of any site you visit from ours, especially since users or community members may access information you post (e.g., email, blog content). We cannot monitor or control how others use your shared information.
      </p>

      {/* Final Disclaimer */}
      <p className="text-xs md:text-sm text-red-600 font-bold mt-8 pt-4 border-t border-gray-300 leading-tight">
        THE SITE IS NOT ENGAGED IN THE OCCUPATION OF STORING, PROCURING OR USAGE OF THE INFORMATION (USER NAMES, PASSWORDS OR EMAILS) THAT YOU MAY ACCESS BY THE USE OF YOUR SOCIAL NETWORKING ACCOUNT FOR THE PURPOSES OF LIKE, TWEETING, +1 BUTTON, OR MENTIONS AND SUBSEQUENTLY CAN'T BE HELD LIABLE FOR THE SAME. THIS DOCUMENT IS AN ELECTRONIC RECORD IN TERMS OF INFORMATION TECHNOLOGY ACT, 2000 AND RULES THEREUNDER AS APPLICABLE AND THE AMENDED PROVISIONS PERTAINING TO ELECTRONIC RECORDS IN VARIOUS STATUTES AS AMENDED BY THE INFORMATION TECHNOLOGY ACT, 2000. THIS ELECTRONIC RECORD IS GENERATED BY A COMPUTER SYSTEM AND DOES NOT REQUIRE ANY PHYSICAL OR DIGITAL SIGNATURES.
      </p>
    </div>
  );
};

export default PrivacyPolicy;